#!/usr/bin/env python3
"""Regenerate docs/function_examples_call_transcript_collector.md.

Every example is a Python expression string that is eval'd against the module;
the printed output is whatever that call returned. Code shown and output shown
cannot drift apart. Rerun after any change to lambda/call_transcript_collector.py:

    python3 scripts/gen_function_examples_call_transcript_collector.py
"""
import os
import sys
import types
from pprint import pformat

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "lambda"))
sys.modules.setdefault("boto3", types.ModuleType("boto3"))  # module imports it; no calls made here
import call_transcript_collector as m  # noqa: E402

OUT = os.path.join(ROOT, "docs", "function_examples_call_transcript_collector.md")

# ---- small hand-made fixtures (mock data, not real AWS output)
segments = [
    {"speaker_label": "spk_0", "transcript": "Hello, how can I help?", "start_time": "0.0", "end_time": "2.0"},
    {"speaker_label": "spk_1", "transcript": "My order is late", "start_time": "2.1", "end_time": "3.0"},
    {"speaker_label": "spk_1", "transcript": "and I am annoyed.", "start_time": "3.0", "end_time": "4.0"},
    {"speaker_label": "spk_0", "transcript": "Sorry, I have refunded you.", "start_time": "4.1", "end_time": "6.0"},
]
transcript = {"results": {
    "transcripts": [{"transcript": "Hello, how can I help? My order is late and I am annoyed. Sorry, I have refunded you."}],
    "audio_segments": segments,
}}
job = {
    "TranscriptionJobName": "feedback-call_042-20260921T120000",
    "Media": {"MediaFileUri": "s3://my-bucket/raw-data/calls/call_042.mp3"},
    "Transcript": {"TranscriptFileUri": "https://s3.us-east-1.amazonaws.com/my-bucket/transcriptions/call_042.json"},
}
failed_job = {
    "TranscriptionJobName": "feedback-call_043-20260921T120500",
    "Media": {"MediaFileUri": "s3://my-bucket/raw-data/calls/call_043.mp3"},
    "FailureReason": "Unsupported audio format.",
}
response = {  # doc 0 and 2 succeed, doc 1 fails
    "ResultList": [
        {"Index": 0, "Sentiment": "NEGATIVE",
         "SentimentScore": {"Positive": 0.02, "Negative": 0.9, "Neutral": 0.06, "Mixed": 0.02}},
        {"Index": 2, "Sentiment": "NEGATIVE",
         "SentimentScore": {"Positive": 0.05, "Negative": 0.8, "Neutral": 0.1, "Mixed": 0.05}},
    ],
    "ErrorList": [{"Index": 1, "ErrorCode": "INTERNAL_SERVER_ERROR"}],
}

ns = dict(vars(m), segments=segments, transcript=transcript, job=job,
          failed_job=failed_job, response=response)
md = []


def text(s):
    md.append(s + "\n")


def ex(expr, show=None):
    """Eval expr; print '>>> expr' + result (or run it as a statement if show is a name)."""
    if show:
        exec(f"{show} = {expr}", ns)
        md.append(f"```python\n{show} = {expr}\n```\n")
        return
    val = eval(expr, ns)
    out = "None" if val is None else pformat(val, sort_dicts=False, width=79)
    md.append(f"```python\n>>> {expr}\n{out}\n```\n")


text("# call_transcript_collector.py — function examples\n\n"
     "Small hand-made inputs, outputs produced by actually calling each function.\n"
     "GENERATED by `scripts/gen_function_examples_call_transcript_collector.py` —\n"
     "do not hand-edit; rerun the script after changing the module.")

text("## 1. `job_status`\n\nWhich job states the Lambda acts on.")
ex('job_status({"TranscriptionJobStatus": "COMPLETED"})')
ex('job_status({"TranscriptionJobStatus": "FAILED"})')
ex('job_status({"TranscriptionJobStatus": "IN_PROGRESS"})')

text("## 2. `parse_s3_uri`\n\nAny of AWS's three URI formats -> (bucket, key).")
ex('parse_s3_uri("s3://my-bucket/raw-data/calls/a.mp3")')
ex('parse_s3_uri("https://s3.us-east-1.amazonaws.com/my-bucket/transcriptions/a.json")')
ex('parse_s3_uri("https://my-bucket.s3.us-east-1.amazonaws.com/transcriptions/a.json")')

text("## 3. `stem_of`\n\nFilename without folder or extension.")
ex('stem_of("raw-data/calls/call_042.mp3")')

text("## 4. `truncate_bytes`\n\nCut to a BYTE limit without splitting a character.")
ex('truncate_bytes("hello world", 5)')
ex('truncate_bytes("café", 4)')

text("## 5. `merge_turns`\n\nJoin consecutive segments from the same speaker. Input: 4 segments, spk_1 split in two.")
ex("merge_turns(segments)", show="turns")
ex("turns")

text("## 6. `infer_roles`\n\nLabelled guess, only for exactly 2 speakers: first = agent. "
     "1 speaker (voicemail) or 3+ (transfer) -> unknown, with the reason in role_method.")
ex("infer_roles(turns)", show="roles")
ex("roles")
ex('infer_roles([{"speaker": "spk_0", "text": "Please call me back."}])')
ex('infer_roles([{"speaker": s, "text": ""} for s in ("spk_0", "spk_1", "spk_2")])')

text("## 7. `pack_turns`\n\nPack whole turns into chunks of <= max_bytes. Splits only BETWEEN turns; "
     "a single turn over the limit is the only thing ever cut, and it is flagged.")
ex('pack_turns(["Hello.", "How can I help?"], 100)')
ex('pack_turns(["a" * 30, "b" * 30], 40)')
ex('pack_turns(["short", "x" * 50, "after"], 40)')

text("## 8. `build_sentiment_docs`\n\nDesign B: documents per speaker ROLE, not per turn. "
     "Comprehend has no speaker field, so each doc carries its slot here.")
ex("build_sentiment_docs(turns, roles)", show="docs")
ex("docs")
ex("build_sentiment_docs(turns, {})")

text("## 9. `batch_chunks`\n\nAt most 25 documents per BatchDetectSentiment call "
     "(a COUNT limit; pack_turns handles the BYTE limit).")
ex("batch_chunks([1, 2, 3, 4, 5], 2)")
ex("[len(group) for group in batch_chunks(list(range(60)))]")

text("## 10. `apply_batch_results`\n\nAttach results to docs BY INDEX. Mock response: docs 0 and 2 succeed, doc 1 fails.")
ex("apply_batch_results(docs, 0, response)", show="errors")
ex("errors")
ex("docs")

text("## 11. `call_sentiment_summary`\n\nOne result per slot; multi-part slots combined by byte-weighted mean. "
     "agent_all failed in Comprehend -> null with a reason, not a guess.")
ex("call_sentiment_summary(docs)")

text("## 12. `build_processed_record`\n\nThe final output file for a completed job.")
ex("build_processed_record(job, transcript, turns, roles, docs, errors)")

text("## 13. `build_failure_record`\n\nWhat a failed job leaves behind (recorded_at is the current UTC time).")
ex('{**build_failure_record(failed_job), "recorded_at": "<current UTC time>"}')

with open(OUT, "w") as f:
    f.write("\n".join(md))
print(f"wrote {os.path.relpath(OUT, ROOT)}")
